
services:
  mariadb:
    build: .
    container_name: mariadb
    ports:
      - "3306:3306"
      - "4444:4444"
      - "4567:4567"
      - "4568:4568"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  mariadb-new-cluster:
    build: .
    container_name: mariadb
    environment:
      MYSQL_ROLE: wsrep-new-cluster
    network_mode: "host"
    volumes:
      - ./mariadb_data:/var/lib/mysql