
services:
  mariadb:
    restart: on-failure
    build: .
    container_name: mariadb
    env_file:
      .env
    network_mode: "host"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./backups:/backups