version: "3.9"

services:
  primary:
    build: .
    container_name: primary
    volumes:
      - primary_data:/var/lib/mysql
    ports:
      - "4306:3306"

  replica:
    build: .
    container_name: replica
    volumes:
      - replica_data:/var/lib/mysql
    ports:
      - "4307:3306"

volumes:
  primary_data:
  replica_data: